laravel/framework:
  source:
    type: git
    url: https://github.com/laravel/framework.git
    reference: master
    success_only: true
  install:
    - composer update --prefer-dist --no-interaction --prefer-stable
    - echo -e "\nREDIS_HOST=127.0.0.1\nREDIS_PORT=6379" >> .env
