preset: psr2

enabled:
  - concat_without_spaces
  - extra_empty_lines
  - long_array_syntax
  - method_separation
  - no_empty_lines_after_phpdocs
  - phpdoc_align
  - phpdoc_indent
  - phpdoc_inline_tag
  - phpdoc_no_access
  - phpdoc_no_package
  - phpdoc_order
  - phpdoc_scalar
  - phpdoc_separation
  - phpdoc_to_comment
  - phpdoc_trim
  - phpdoc_type_to_var
  - phpdoc_types
  - phpdoc_var_without_name
  - return
  - single_quote
  - spaces_cast
  - unalign_double_arrow
  - unalign_equals
  - unused_use
  - whitespacy_lines
