name: Documentation

on: [ pull_request, push ]

jobs:
  sponsors:
    name: Update documentation

    if: github.repository == 'briannesbitt/Carbon'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3.19
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        shell: bash
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: "documentation-${{ hashFiles('**/composer.json') }}"
          restore-keys: "documentation-${{ hashFiles('**/composer.json') }}"

      - name: Install dependencies
        uses: nick-fields/retry@v3
        if: steps.composer-cache.outputs.cache-hit != 'true'
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: composer update --prefer-dist --no-progress --prefer-stable

      - name: Releases
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 2
          command: composer releases

      - name: php tools/release.php
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 2
          command: php tools/release.php

      - name: Update
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 2
          command: composer update

      - name: History
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 2
          command: composer history

      - name: Generate
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 2
          command: composer generate

      - name: Check
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 2
          command: composer check

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: job/update-documentation
          commit-message: Update documentation
          title: Update documentation
          body: Monthly automated documentation update
          assignees: kylekatarnls
          reviewers: kylekatarnls
          add-paths: :!history.json
